version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
